language: ruby
cache: bundler
rvm:
- 2.4.0
before_script:
- bundle exec rake db:create --all
- bundle exec rake db:migrate
script:
- bundle exec rake ci:tests
deploy:
  provider: heroku
  api_key:
    secure: STg94s64NzHbFiuCK7OqKYw1/U2w/J2ZTTmeyvgMe3fpqtra7pVsdY9bmLrLWxz1ODSnAonXw9qyMWzuncVkd88dN/R/0fb85u1B/gCeeC2XUQc+EvJ9kN/Ylf2Pm7LHflt2fSZVaJRABehUi5bVgp52SNzdHxqnlNW0JWzCL71rl+Ms+aonA6dLOgZ8Rwum/JAFgtS7EHUSWUPwmQ523t6GWc+Lj9bHX5Xbl7b+GQb8hMIjB4uMs4HtHXvST9G1+SJ3wKPd7m4d8McmaUX1wBY5EQOq1fhh1fg2DzDbKCTmPsWmqr9mf4Tumk5FrZYNxvtiV8QOdLhJmbo1ebLnjVLILXFoDMOe2+9JhQeHlmBy+r7t0ThNTWA8GzTQiF69bbB1ylJVYgTImj5jM1RhpuUBFvUUHh+5aBHNxQY20LLTzcfKnu0Ci9M8SqqkQl19zy4utUqUjVWkto8Fxigh4J1rwTWsXPKn5dsdEYCnV+y2PmttG2CeJ0EZw77UFgsaczdldC1MBpeyP1kYipvNj+pEjJC5WsA8fP+iFRFUjzkxfcr4a4qsEHYF16RnRWkcGxK2uKfDXleaUD/X4Hao7cuhuO0V9ivhTA+cOc6Q+XRXanCJmjDLCBOUs+skmwEw6Wg0MsO6kk3YsNm1pg+KQuu6vOW4s3fJGSriQGF2duc=
  app: railsmessagingaugust17
  on:
    repo: CraftAcademy/rails_messaging_august_17
    branch: develop
